version: '3.7'

networks:
  users:

services:
  users-service:
    build: 
      context: ./userServices
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - users
    environment:
      - spring.datasource.url=jdbc:mysql://users-db:3306/teste?allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.password=teste
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.show-sql=true
      - security.basic.enabled=false
    depends_on:
      - users-db
  users-db:
    container_name: users-db
    image: mysql
    restart: always
    environment:
      MYSQL_USER: teste
      MYSQL_DATABASE: teste
      MYSQL_PASSWORD: teste
      MYSQL_ROOT_PASSWORD: teste
    networks:
      - users
    ports:
      - "3306:3306"